-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 19:46:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LivrosApp_Db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LivrosApp_Db` ;

-- -----------------------------------------------------
-- Schema LivrosApp_Db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LivrosApp_Db` DEFAULT CHARACTER SET utf8 ;
USE `LivrosApp_Db` ;

-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `flag` TINYINT(1) NOT NULL,
  `avatar` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`generos` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`livros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`livros` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `generos_id` INT NULL,
  `usuarios_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(500) NULL,
  `sinopse` VARCHAR(500) NOT NULL,
  `tags` VARCHAR(45) NOT NULL,
  `avaliacao_geral` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `generos_id`),
  INDEX `fk_livros_generos1_idx` (`generos_id` ASC) VISIBLE,
  INDEX `fk_livros_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_livros_generos1`
    FOREIGN KEY (`generos_id`)
    REFERENCES `LivrosApp_Db`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `LivrosApp_Db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`capitulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`capitulos` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`capitulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `livros_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ordem_capitulo` VARCHAR(45) NOT NULL,
  `upload` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_capitulos_livros1_idx` (`livros_id` ASC) VISIBLE,
  CONSTRAINT `fk_capitulos_livros1`
    FOREIGN KEY (`livros_id`)
    REFERENCES `LivrosApp_Db`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capitulos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `comentarios` VARCHAR(250) NOT NULL,
  `data_comentario` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `capitulos_id`, `usuarios_id`),
  INDEX `fk_comentarios_capitulos1_idx` (`capitulos_id` ASC) VISIBLE,
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_capitulos1`
    FOREIGN KEY (`capitulos_id`)
    REFERENCES `LivrosApp_Db`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `LivrosApp_Db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`Perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`Perguntas` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`Perguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capitulos_id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `capitulos_id`),
  INDEX `fk_enquetes_capitulos1_idx` (`capitulos_id` ASC) VISIBLE,
  CONSTRAINT `fk_enquetes_capitulos1`
    FOREIGN KEY (`capitulos_id`)
    REFERENCES `LivrosApp_Db`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`favoritos` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`favoritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `livros_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`, `livros_id`),
  INDEX `fk_favoritos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_favoritos_livros1_idx` (`livros_id` ASC) VISIBLE,
  CONSTRAINT `fk_favoritos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `LivrosApp_Db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_livros1`
    FOREIGN KEY (`livros_id`)
    REFERENCES `LivrosApp_Db`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `capitulos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`, `capitulos_id`),
  INDEX `fk_avaliacao_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_avaliacao_capitulos1_idx` (`capitulos_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `LivrosApp_Db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_capitulos1`
    FOREIGN KEY (`capitulos_id`)
    REFERENCES `LivrosApp_Db`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`Opcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`Opcao` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`Opcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opcao` VARCHAR(255) NOT NULL,
  `Perguntas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Perguntas_id`),
  INDEX `fk_Opcao_Perguntas1_idx` (`Perguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Opcao_Perguntas1`
    FOREIGN KEY (`Perguntas_id`)
    REFERENCES `LivrosApp_Db`.`Perguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LivrosApp_Db`.`Votação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LivrosApp_Db`.`Votação` ;

CREATE TABLE IF NOT EXISTS `LivrosApp_Db`.`Votação` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `Perguntas_id` INT NOT NULL,
  `Opcao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`, `Perguntas_id`, `Opcao_id`),
  INDEX `fk_participacao_enquete_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_Votação_Perguntas1_idx` (`Perguntas_id` ASC) VISIBLE,
  INDEX `fk_Votação_Opcao1_idx` (`Opcao_id` ASC) VISIBLE,
  CONSTRAINT `fk_participacao_enquete_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `LivrosApp_Db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votação_Perguntas1`
    FOREIGN KEY (`Perguntas_id`)
    REFERENCES `LivrosApp_Db`.`Perguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votação_Opcao1`
    FOREIGN KEY (`Opcao_id`)
    REFERENCES `LivrosApp_Db`.`Opcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
